language: objective-c
osx_image: xcode9.2

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - echo -e "machine github.com\n  login AppRelated\n  password $GITHUB_PASSWORD" >> ~/.netrc

install:
  - bundle install
  - yarn install

before_script:
  - fastlane env

jobs:
  include:
    - stage: release
      script: cd ios && fastlane beta
      if: branch = develop

    - stage: release
      script: cd ios && fastlane appstore
      if: branch = master
